---
- name: Starting Mesos slave container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      MESOS_HOSTNAME: "{{ inventory_hostname }}"
      MESOS_IP: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
      MESOS_MASTER: "zk://{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }}{% endfor %}:2181/mesos"
      MESOS_LOG_DIR: "/var/log/mesos"
      MESOS_LOGGING_LEVEL: "INFO"
    image: "{{ mesos_slave_image_full }}"
    name: "mesos_slave"
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
