{% set mysql_dir = 'mysql' if kolla_base_distro in ['ubuntu', 'debian'] else '' %}
config:
  mariadb:
    mariadb:
      kolla_mesos_start.py:
        source: config/kolla_mesos_start.py
        dest: /kolla_mesos_start.py
      galera.cnf.j2:
        source: config/mariadb/templates/galera.cnf.j2
        dest: /etc/{{ mysql_dir }}/my.cnf"
        owner: mysql
        perm: "0600"
commands:
  mariadb:
    mariadb:
      final:
        command: /usr/bin/mysqld_safe
        run_once: False
        requires: [/kolla/variables/mariadb_bootstrap.done]
